name: first workflow

on: push

jobs: 
    first_jobs:
       runs-on: ubuntu-latest
       steps:
         - name: Checkout Repo
           uses: actions/checkout@v4

         - name: List and Read multiline files
           run: | 
                echo "My first github actions job"
                ls -ltra
                cat README.md
         
         - name: Generate ASCII Artwork
           run: cowsay -f dragon "Run for cover, I am a Dragon...RawR" >> drago.txt
           
         #- name: List files
         # run: ls

         #- name: Read File
         #  run: cat README.md 
              
