name: Generate ASCII Artwork 2

on: push

jobs:
    ascii-job:
        runs-on: ubuntu-latest
        steps:
        -    name: Checkout Repo
             uses: actions/checkout@v4

        -    name: List all files in the repository
             run: ls -ltra

        -    name: Executing Shell script
             run: ./ascii-script.sh
