name: Matrix configuration

on:
    push:
    workflow_dispatch: 
        
jobs:
    deploy-job:
        strategy:
            fail-fast: false
            max-parallel: 3
            matrix:
                os: [ubuntu-latest,windows-latest,macos-latest]
                images: [hello-world,alpine]
                exclude:
                    - name: alpine
                      os: windows-latest
        runs-on: ${{matrix.os}}
        steps:
        -    name: docker details
             run: docker info
        -    name: running docker immage on ${{matrix.os}}
             run: docker run ${{matrix.images}}

